import { IDropSession } from "@/features/dropoff/types/types.dropoff";

export const MOCK_SESSIONS: IDropSession[] = [
  {
    code: "ABC123",
    guardianName: "Mr. Johnson",
    phone: "08011223344",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "XYZ789",
    guardianName: "Mrs. Chioma",
    phone: "09099887766",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "LMN456",
    guardianName: "Mr. Adewale",
    phone: "08134567890",
    childCount: 3,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "JKL321",
    guardianName: "Mrs. Uche",
    phone: "07056789012",
    childCount: 2,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "DEF789",
    guardianName: "Mr. Obi",
    phone: "08033445566",
    childCount: 1,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "GHJ567",
    guardianName: "Mrs. Amina",
    phone: "09077665544",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "QWE234",
    guardianName: "Mr. Bello",
    phone: "08022334455",
    childCount: 4,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "RTY678",
    guardianName: "Mrs. Grace",
    phone: "08111223344",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "UIO890",
    guardianName: "Mr. Musa",
    phone: "07099887766",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "ASD345",
    guardianName: "Mrs. Ezinne",
    phone: "09012345678",
    childCount: 3,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "ZXC654",
    guardianName: "Mr. Okoro",
    phone: "08055667788",
    childCount: 2,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "VBN321",
    guardianName: "Mrs. Fatima",
    phone: "08178899001",
    childCount: 1,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "PLM987",
    guardianName: "Mr. Dapo",
    phone: "09066554433",
    childCount: 2,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "KJH123",
    guardianName: "Mrs. Onome",
    phone: "07033445522",
    childCount: 3,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "ERT456",
    guardianName: "Mr. Kelvin",
    phone: "08199988877",
    childCount: 1,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "TYU678",
    guardianName: "Mrs. Nneka",
    phone: "09055667788",
    childCount: 4,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "IOP890",
    guardianName: "Mr. Sunday",
    phone: "08011221122",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "BNM456",
    guardianName: "Mrs. Peace",
    phone: "08144332211",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "CDE789",
    guardianName: "Mr. Hassan",
    phone: "07011223344",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "FGH012",
    guardianName: "Mrs. Jane",
    phone: "09066778899",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "AQC123",
    guardianName: "Mr. Johnson",
    phone: "08011223344",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "XEZ789",
    guardianName: "Mrs. Chioma",
    phone: "09099887766",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "LFN456",
    guardianName: "Mr. Adewale",
    phone: "08134567890",
    childCount: 3,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "JOL321",
    guardianName: "Mrs. Uche",
    phone: "07056789012",
    childCount: 2,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "DEQ789",
    guardianName: "Mr. Obi",
    phone: "08033445566",
    childCount: 1,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "GZJ567",
    guardianName: "Mrs. Amina",
    phone: "09077665544",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "QLE234",
    guardianName: "Mr. Bello",
    phone: "08022334455",
    childCount: 4,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "RXY678",
    guardianName: "Mrs. Grace",
    phone: "08111223344",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "UHO890",
    guardianName: "Mr. Musa",
    phone: "07099887766",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "AWD345",
    guardianName: "Mrs. Ezinne",
    phone: "09012345678",
    childCount: 3,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "ZIC654",
    guardianName: "Mr. Okoro",
    phone: "08055667788",
    childCount: 2,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "VNN321",
    guardianName: "Mrs. Fatima",
    phone: "08178899001",
    childCount: 1,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "PAM987",
    guardianName: "Mr. Dapo",
    phone: "09066554433",
    childCount: 2,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "KUH123",
    guardianName: "Mrs. Onome",
    phone: "07033445522",
    childCount: 3,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "EBT456",
    guardianName: "Mr. Kelvin",
    phone: "08199988877",
    childCount: 1,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "TVU678",
    guardianName: "Mrs. Nneka",
    phone: "09055667788",
    childCount: 4,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "IPP890",
    guardianName: "Mr. Sunday",
    phone: "08011221122",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "BLM456",
    guardianName: "Mrs. Peace",
    phone: "08144332211",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
  {
    code: "CAE789",
    guardianName: "Mr. Hassan",
    phone: "07011223344",
    childCount: 2,
    status: "awaiting",
    createdAt: new Date().toISOString(),
  },
  {
    code: "FBH012",
    guardianName: "Mrs. Jane",
    phone: "09066778899",
    childCount: 1,
    status: "picked_up",
    createdAt: new Date().toISOString(),
  },
];
